{% set name = "pokemonpy" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pokemonpy-{{ version }}.tar.gz
  sha256: 68b6a2b1b95eb8b4bc945ad21f5ae458f8ef6a5905b13723d79fade91c55bdae

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - numpy >=1.26.4,<1.27.dev0

test:
  imports:
    - pokemonpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/4ntoined/pokemonpy-package
  summary: A package that contains a Pokémon simulation game.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 4ntoined
