{% set name = "pokemonpy" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pokemonpy-{{ version }}.tar.gz
  sha256: eb40f039de26279b6e18f7e5318a91dcc393c13a4a53a6209b13d1b9eba1a481

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - numpy >=1.26.4,<1.27.dev0

test:
  imports:
    - pokemonpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/4ntoined/pokemonpy-package
  summary: A package that contains a Pokémon simulation game.
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - 4ntoined
